-- demo_llvm.lua — 一键流程: annotate → split → lift → LLVM 优化 → 输出汇编
-- 用法: 在引擎中执行此脚本即可

-- ── 第1步: 执行前置脚本 ──
dofile("scripts\\annotate.lua")
dofile("scripts\\split_handlers.lua")

-- ── 第2步: 检查 LLVM ──
if not llvm_available() then
    log("[error] LLVM-C.dll 未加载，无法继续")
    return
end
log("\n[LLVM] LLVM-C.dll 已就绪")

-- ── 第3步: 生成 LLVM IR（内联 lift 逻辑）──

dofile("scripts\\tools.lua")

local pushes, vmstack_base, rsp_to_name = get_init_pushes()
local vs_reg = get_vmstack_reg()

local function parse_imm(detail)
    local hex = detail:match("^%(0x(%x+)%)")
    if not hex then hex = detail:match("=0x(%x+)") end
    if hex then return tonumber(hex, 16) end
    return nil
end

local function parse_rsp_offset(detail)
    local hex = detail:match("rsp%+0x(%x+)")
    if hex then return tonumber(hex, 16) end
    return nil
end

-- 找 vExit
local vexit_idx = nil
for hi = 1, #handlers do
    if handlers[hi].type == "vExit" then vexit_idx = hi; break end
end
if not vexit_idx then log("[error] 未找到 vExit"); return end

local exit_restore_start = vexit_idx - 1
while exit_restore_start >= 1 and handlers[exit_restore_start].type == "vPushReg" do
    exit_restore_start = exit_restore_start - 1
end
exit_restore_start = exit_restore_start + 1

-- EXIT 映射
local vexit_h = handlers[vexit_idx]
local exit_pop_regs = {}
for _, ri in ipairs(vexit_h.row_indices) do
    local row = rows[ri]
    if not row.is_junk and row.mnemonic == "pop" and #row.operands >= 1
       and row.operands[1].type == "reg" then
        table.insert(exit_pop_regs, row.operands[1].reg)
    elseif not row.is_junk and row.mnemonic == "popfq" then
        table.insert(exit_pop_regs, "rflags")
    end
end

local exit_push_offsets = {}
for hi = exit_restore_start, vexit_idx - 1 do
    local off = parse_rsp_offset(handlers[hi].detail or "")
    if off then table.insert(exit_push_offsets, off) end
end

local off_to_exit = {}
if #exit_push_offsets == #exit_pop_regs then
    for i = 1, #exit_push_offsets do
        local push_off = exit_push_offsets[#exit_push_offsets - i + 1]
        off_to_exit[push_off] = exit_pop_regs[i]
    end
end

local off_to_init = {}
for hi = 2, #handlers do
    local h = handlers[hi]
    if h.type ~= "vPop" then break end
    local det = h.detail or ""
    local m = det:match("%((%a%w*)%)")
    local tgt_off = parse_rsp_offset(det)
    if m and tgt_off then off_to_init[tgt_off] = m end
end

-- 收集所有 slot offset
local all_offsets = {}
local offset_set = {}
local function register_offset(off)
    if off and not offset_set[off] then
        offset_set[off] = true
        table.insert(all_offsets, off)
    end
end
for hi = 2, #handlers do
    if handlers[hi].type ~= "vPop" then break end
    register_offset(parse_rsp_offset(handlers[hi].detail or ""))
end
local compute_start = nil
for hi = 2, #handlers do
    if handlers[hi].type ~= "vPop" then compute_start = hi; break end
end
local compute_end = exit_restore_start - 1
for hi = compute_start, compute_end do
    register_offset(parse_rsp_offset(handlers[hi].detail or ""))
end
for _, off in ipairs(exit_push_offsets) do register_offset(off) end
table.sort(all_offsets)

local function slot_name(off) return string.format("slot_0x%X", off) end

-- EXIT 寄存器列表
local exit_regs = {}
local exit_regs_set = {}
for _, name in pairs(off_to_exit) do
    if name ~= "rflags" and not exit_regs_set[name] then
        exit_regs_set[name] = true
        table.insert(exit_regs, name)
    end
end
table.sort(exit_regs)

-- 生成 IR
local ir = {}
local ssa_id = 0
local function new_ssa() ssa_id = ssa_id + 1; return "%" .. ssa_id end
local function emit(line) table.insert(ir, "  " .. line) end
local stack = {}
local function spush(val) table.insert(stack, val) end
local function spop()
    if #stack == 0 then return "undef" end
    return table.remove(stack)
end

table.insert(ir, "; Generated by demo_llvm.lua (inline-asm, modified-only)")
table.insert(ir, "")
table.insert(ir, "define void @vmp_block() {")
table.insert(ir, "entry:")

for _, off in ipairs(all_offsets) do
    emit(string.format("%%%s = alloca i64, align 8", slot_name(off)))
end

-- 用 inline asm 从 INIT 物理寄存器读取初始值
emit("")
local init_reg_reads = {}
local init_regs_ordered = {}
local function need_reg_read(reg)
    if not reg or reg == "rflags" or init_reg_reads[reg] then return end
    init_reg_reads[reg] = true
    table.insert(init_regs_ordered, reg)
end
for _, off in ipairs(all_offsets) do
    need_reg_read(off_to_init[off])
end

local reg_to_ssa = {}
for _, reg in ipairs(init_regs_ordered) do
    local v = new_ssa()
    emit(string.format('%s = call i64 asm sideeffect "", "={%s}"()', v, reg))
    reg_to_ssa[reg] = v
end

emit("")
for _, off in ipairs(all_offsets) do
    local init_reg = off_to_init[off]
    if init_reg and init_reg ~= "rflags" and reg_to_ssa[init_reg] then
        emit(string.format("store i64 %s, ptr %%%s", reg_to_ssa[init_reg], slot_name(off)))
    else
        emit(string.format("store i64 0, ptr %%%s", slot_name(off)))
    end
end

local modified_slots = {}

emit("")
for hi = compute_start, compute_end do
    local h = handlers[hi]
    local typ = h.type
    local det = h.detail or ""
    emit(string.format("; [%d] %s %s", hi - 1, typ, det))

    if typ == "vPushReg" then
        local off = parse_rsp_offset(det)
        if off and offset_set[off] then
            local v = new_ssa()
            emit(string.format("%s = load i64, ptr %%%s", v, slot_name(off)))
            spush(v)
        else spush("undef") end

    elseif typ == "vPushImm64" or typ == "vPushImm32" or typ == "vPushImm16" then
        local imm = parse_imm(det)
        spush(imm and tostring(imm) or "0")

    elseif typ == "vPushVSP" then
        spush("__VSP__")

    elseif typ == "vPop" then
        local val = spop()
        if val == "__VSP__" then
            local v = new_ssa()
            emit(string.format('%s = call i64 asm sideeffect "", "={%s}"()  ; vPushVSP materialized', v, vs_reg))
            val = v
        end
        local tgt_off = parse_rsp_offset(det)
        if tgt_off and offset_set[tgt_off] then
            emit(string.format("store i64 %s, ptr %%%s", val, slot_name(tgt_off)))
            modified_slots[tgt_off] = true
        end

    elseif typ == "vAdd" or typ == "vSub" or typ == "vAnd" or typ == "vOr" or typ == "vXor" then
        local b, a = spop(), spop()
        local r = new_ssa()
        local op = ({vAdd="add",vSub="sub",vAnd="and",vOr="or",vXor="xor"})[typ]
        emit(string.format("%s = %s i64 %s, %s", r, op, a, b))
        spush(r); spush("0")

    elseif typ == "vNand" then
        local b, a = spop(), spop()
        local t = new_ssa()
        local r = new_ssa()
        emit(string.format("%s = and i64 %s, %s", t, a, b))
        emit(string.format("%s = xor i64 %s, -1", r, t))
        spush(r); spush("0")

    elseif typ == "vNor" then
        local b, a = spop(), spop()
        local t = new_ssa()
        local r = new_ssa()
        emit(string.format("%s = or i64 %s, %s", t, a, b))
        emit(string.format("%s = xor i64 %s, -1", r, t))
        spush(r); spush("0")

    elseif typ == "vShr" or typ == "vShl" or typ == "vSar" then
        local b, a = spop(), spop()
        local r = new_ssa()
        local op = ({vShr="lshr",vShl="shl",vSar="ashr"})[typ]
        emit(string.format("%s = %s i64 %s, %s", r, op, a, b))
        spush(r); spush("0")

    elseif typ == "vNot" then
        local r = new_ssa()
        emit(string.format("%s = xor i64 %s, -1", r, spop()))
        spush(r); spush("0")

    elseif typ == "vNeg" then
        local r = new_ssa()
        emit(string.format("%s = sub i64 0, %s", r, spop()))
        spush(r); spush("0")

    elseif typ == "vMul" or typ == "vImul" then
        local b, a = spop(), spop()
        local r = new_ssa()
        emit(string.format("%s = mul i64 %s, %s", r, a, b))
        spush(r); spush("0")

    elseif typ:match("^vStore") then
        local addr, val = spop(), spop()
        local bits = typ:match("vStore(%d+)")
        local ptr = new_ssa()
        emit(string.format("%s = inttoptr i64 %s to ptr", ptr, addr))
        if bits == "64" then
            emit(string.format("store i64 %s, ptr %s", val, ptr))
        else
            local t = new_ssa()
            local ty = ({["8"]="i8",["16"]="i16",["32"]="i32"})[bits] or "i32"
            emit(string.format("%s = trunc i64 %s to %s", t, val, ty))
            emit(string.format("store %s %s, ptr %s", ty, t, ptr))
        end

    elseif typ:match("^vLoad") then
        local addr = spop()
        local bits = typ:match("vLoad(%d+)")
        if addr == "__VSP__" then
            -- vPushVSP + vLoad = dup 栈顶
            if #stack > 0 then
                emit(string.format("; vPushVSP+vLoad%s → dup stack top", bits))
                spush(stack[#stack])
            else
                spush("undef")
            end
        else
            local ptr = new_ssa()
            emit(string.format("%s = inttoptr i64 %s to ptr", ptr, addr))
            if bits == "64" then
                local v = new_ssa()
                emit(string.format("%s = load i64, ptr %s", v, ptr))
                spush(v)
            else
                local t = new_ssa()
                local ty = ({["8"]="i8",["16"]="i16",["32"]="i32"})[bits] or "i32"
                emit(string.format("%s = load %s, ptr %s", t, ty, ptr))
                local ext = new_ssa()
                emit(string.format("%s = zext %s %s to i64", ext, ty, t))
                spush(ext)
            end
        end
    end
end

emit("")
emit("; write only modified registers via inline asm")
for off, reg in pairs(off_to_exit) do
    if reg ~= "rflags" and offset_set[off] and modified_slots[off] then
        local v = new_ssa()
        emit(string.format("%s = load i64, ptr %%%s", v, slot_name(off)))
        emit(string.format('call void asm sideeffect "", "{%s}"(i64 %s)', reg, v))
    end
end
emit("ret void")
table.insert(ir, "}")

local ir_text = table.concat(ir, "\n") .. "\n"
log(string.format("\n[LLVM] 生成 IR: %d 行, 符号栈剩余 %d", #ir, #stack))

-- ── 第4步: 调用 LLVM 优化并输出汇编 ──

log("[LLVM] 正在优化 (O2)...")
local asm_text, err = llvm_emit_asm(ir_text, 2)
if err then
    log("[LLVM] 错误: " .. err)
    return
end

-- 写 IR 到文件（不在 log 里刷屏）
local opt_ir, err2 = llvm_optimize_ir(ir_text, 2)
if opt_ir then
    local f = io.open("vmp_optimized.ll", "w")
    if f then f:write(opt_ir); f:close() end
    log("[LLVM] 优化后 IR 已写入 vmp_optimized.ll")
end

-- 写汇编到文件
local f = io.open("vmp_optimized.s", "w")
if f then f:write(asm_text); f:close() end
log("[LLVM] 优化后汇编已写入 vmp_optimized.s")

-- 十进制转十六进制（含负数处理）
local function dec_to_hex(s)
    local n = tonumber(s)
    if not n then return s end
    if n < 0 then
        -- 根据大小选择位宽：8/32/64
        if n >= -128 then
            n = n + 256
        elseif n >= -2147483648 then
            n = n + 4294967296
        else
            n = n + 0x10000000000000000
        end
    end
    return string.format("0x%X", n)
end

local function convert_line(line)
    line = line:gsub("%s+#.*$", "")
    -- 把所有独立的十进制数（负数或大正数）转十六进制
    -- 匹配逗号后的数字、方括号内的偏移等
    line = line:gsub(",%s*(-?%d+)$", function(num)
        local n = tonumber(num)
        if n and (n < 0 or n > 255) then return ", " .. dec_to_hex(num) end
        return ", " .. num
    end)
    line = line:gsub(",%s*(-?%d+)(,)", function(num, comma)
        local n = tonumber(num)
        if n and (n < 0 or n > 255) then return ", " .. dec_to_hex(num) .. comma end
        return ", " .. num .. comma
    end)
    line = line:gsub("],%s*(-?%d+)", function(num)
        local n = tonumber(num)
        if n and (n < 0 or n > 255) then return "], " .. dec_to_hex(num) end
        return "], " .. num
    end)
    line = line:gsub("retq", "ret")
    return line
end

-- 在 log 里只显示有效汇编指令（过滤噪音）
log("\n[LLVM] ═══ 优化后汇编 ═══\n")
local in_func = false
for line in asm_text:gmatch("[^\n]+") do
    if line:match("^vmp_block:") then
        in_func = true
    elseif line:match("^%s+retq") and in_func then
        log("    ret")
        in_func = false
    elseif in_func
        and not line:match("^#")
        and not line:match("^%s*#")
        and not line:match("^%s+pushq")
        and not line:match("^%s+popq")
        and not line:match("^%s*$") then
        log(convert_line(line))
    end
end

log("\n[ok] demo_llvm.lua 完成")
