dofile("scripts\\tools.lua")

-- ═══════════════════════════════════════════════════════
-- lift_to_llvm.lua — 每个 slot 独立 alloca，EXIT 映射输出
-- 前置: 先运行 annotate.lua + split_handlers.lua
-- ═══════════════════════════════════════════════════════

local pushes, vmstack_base, rsp_to_name = get_init_pushes()
local vs_reg = get_vmstack_reg()
if not vs_reg then log("[error] 未找到 vmStack 寄存器"); return end

local function parse_imm(detail)
    local hex = detail:match("^%(0x(%x+)%)")
    if not hex then hex = detail:match("=0x(%x+)") end
    if hex then return tonumber(hex, 16) end
    return nil
end

local function parse_rsp_offset(detail)
    local hex = detail:match("rsp%+0x(%x+)")
    if hex then return tonumber(hex, 16) end
    return nil
end

-- ── 找 vExit 和恢复序列 ──

local vexit_idx = nil
for hi = 1, #handlers do
    if handlers[hi].type == "vExit" then vexit_idx = hi; break end
end
if not vexit_idx then log("[error] 未找到 vExit"); return end

local exit_restore_start = vexit_idx - 1
while exit_restore_start >= 1 and handlers[exit_restore_start].type == "vPushReg" do
    exit_restore_start = exit_restore_start - 1
end
exit_restore_start = exit_restore_start + 1

local vexit_h = handlers[vexit_idx]
local exit_pop_regs = {}
for _, ri in ipairs(vexit_h.row_indices) do
    local row = rows[ri]
    if not row.is_junk and row.mnemonic == "pop" and #row.operands >= 1
       and row.operands[1].type == "reg" then
        table.insert(exit_pop_regs, row.operands[1].reg)
    elseif not row.is_junk and row.mnemonic == "popfq" then
        table.insert(exit_pop_regs, "rflags")
    end
end

local exit_push_offsets = {}
for hi = exit_restore_start, vexit_idx - 1 do
    local off = parse_rsp_offset(handlers[hi].detail or "")
    if off then table.insert(exit_push_offsets, off) end
end

-- EXIT 映射: slot offset → CPU 寄存器
local off_to_exit = {}
if #exit_push_offsets == #exit_pop_regs then
    for i = 1, #exit_push_offsets do
        local push_off = exit_push_offsets[#exit_push_offsets - i + 1]
        off_to_exit[push_off] = exit_pop_regs[i]
    end
end

-- INIT 映射
local off_to_init = {}
for hi = 2, #handlers do
    local h = handlers[hi]
    if h.type ~= "vPop" then break end
    local det = h.detail or ""
    local m = det:match("%((%a%w*)%)")
    local tgt_off = parse_rsp_offset(det)
    if m and tgt_off then
        off_to_init[tgt_off] = m
    end
end

-- ── 收集所有出现过的 slot offset ──

local all_offsets = {}
local offset_set = {}
local function register_offset(off)
    if off and not offset_set[off] then
        offset_set[off] = true
        table.insert(all_offsets, off)
    end
end

-- 从 init vPop 收集
for hi = 2, #handlers do
    local h = handlers[hi]
    if h.type ~= "vPop" then break end
    local off = parse_rsp_offset(h.detail or "")
    register_offset(off)
end

-- 从计算区间收集
local compute_start = nil
for hi = 2, #handlers do
    if handlers[hi].type ~= "vPop" then compute_start = hi; break end
end
local compute_end = exit_restore_start - 1

for hi = compute_start, compute_end do
    local h = handlers[hi]
    local off = parse_rsp_offset(h.detail or "")
    register_offset(off)
end

-- 从 exit restore 收集
for _, off in ipairs(exit_push_offsets) do register_offset(off) end

table.sort(all_offsets)

-- slot 名称
local function slot_name(off) return string.format("slot_0x%X", off) end

-- 收集 EXIT 寄存器列表（输出参数）
local exit_regs = {}
local exit_regs_set = {}
for _, name in pairs(off_to_exit) do
    if name ~= "rflags" and not exit_regs_set[name] then
        exit_regs_set[name] = true
        table.insert(exit_regs, name)
    end
end
table.sort(exit_regs)

-- ── LLVM IR ──

local ir = {}
local ssa_id = 0
local function new_ssa() ssa_id = ssa_id + 1; return "%" .. ssa_id end
local function emit(line) table.insert(ir, "  " .. line) end

local stack = {}
local function spush(val) table.insert(stack, val) end
local function spop()
    if #stack == 0 then log("[warn] stack underflow"); return "undef" end
    return table.remove(stack)
end

-- 收集所有出现的物理寄存器名（去重，排序）
local all_regs = {}
local all_regs_set = {}
local function collect_reg(name)
    if not name or name == "rflags" or all_regs_set[name] then return end
    all_regs_set[name] = true
    table.insert(all_regs, name)
end
for _, off in ipairs(all_offsets) do
    collect_reg(off_to_init[off])
    collect_reg(off_to_exit[off])
end
table.sort(all_regs)

-- 寄存器名 → struct 字段索引
local reg_to_idx = {}
for i, name in ipairs(all_regs) do
    reg_to_idx[name] = i - 1
end

-- 函数签名: 接收 CPU 状态 struct 指针
table.insert(ir, "; Generated by vmp_engine lift_to_llvm.lua (struct context)")
table.insert(ir, "")

-- struct 定义: { i64, i64, i64, ... }
local fields = {}
for _ = 1, #all_regs do table.insert(fields, "i64") end
table.insert(ir, string.format("%%struct.CpuState = type { %s }", table.concat(fields, ", ")))
table.insert(ir, "")

-- 字段注释
for i, name in ipairs(all_regs) do
    table.insert(ir, string.format("; field %d = %s", i - 1, name))
end
table.insert(ir, "")

table.insert(ir, "define x86_64_sysvcc void @vmp_block(ptr %ctx) {")
table.insert(ir, "entry:")

-- 每个 slot 一个 alloca
for _, off in ipairs(all_offsets) do
    emit(string.format("%%%s = alloca i64, align 8", slot_name(off)))
end

-- 从 struct 读取 INIT 寄存器值，存入 slot
emit("")
emit("; load registers from context struct → slots")
local reg_ssa_cache = {}
for _, off in ipairs(all_offsets) do
    local init_reg = off_to_init[off]
    if init_reg and init_reg ~= "rflags" and reg_to_idx[init_reg] then
        -- 每个寄存器只 GEP+load 一次
        if not reg_ssa_cache[init_reg] then
            local gep = new_ssa()
            local val = new_ssa()
            emit(string.format("%s = getelementptr inbounds %%struct.CpuState, ptr %%ctx, i32 0, i32 %d", gep, reg_to_idx[init_reg]))
            emit(string.format("%s = load i64, ptr %s  ; %s", val, gep, init_reg))
            reg_ssa_cache[init_reg] = val
        end
        emit(string.format("store i64 %s, ptr %%%s", reg_ssa_cache[init_reg], slot_name(off)))
    else
        emit(string.format("store i64 0, ptr %%%s", slot_name(off)))
    end
end

emit("")
emit("; ═══ computation ═══")

local modified_slots = {}

-- 遍历 handler
for hi = compute_start, compute_end do
    local h = handlers[hi]
    local typ = h.type
    local det = h.detail or ""

    emit(string.format("; [%d] %s %s", hi - 1, typ, det))

    if typ == "vPushReg" then
        local off = parse_rsp_offset(det)
        if off and offset_set[off] then
            local v = new_ssa()
            emit(string.format("%s = load i64, ptr %%%s", v, slot_name(off)))
            spush(v)
        else
            spush("undef")
        end

    elseif typ == "vPushImm64" or typ == "vPushImm32" or typ == "vPushImm16" then
        local imm = parse_imm(det)
        spush(imm and tostring(imm) or "0")

    elseif typ == "vPushVSP" then
        local v = new_ssa()
        emit(string.format('%s = call i64 asm sideeffect "", "={%s}"()  ; vPushVSP', v, vs_reg))
        spush(v)

    elseif typ == "vPop" then
        local val = spop()
        local tgt_off = parse_rsp_offset(det)
        if tgt_off and offset_set[tgt_off] then
            emit(string.format("store i64 %s, ptr %%%s", val, slot_name(tgt_off)))
            modified_slots[tgt_off] = true
        else
            emit(string.format("; discard %s", val))
        end

    elseif typ == "vAdd" or typ == "vSub" or typ == "vAnd"
        or typ == "vOr" or typ == "vXor" then
        local b = spop()
        local a = spop()
        local result = new_ssa()
        local op_map = { vAdd="add", vSub="sub", vAnd="and", vOr="or", vXor="xor" }
        emit(string.format("%s = %s i64 %s, %s", result, op_map[typ], a, b))
        spush(result)
        spush("0")

    elseif typ == "vNand" then
        local b = spop()
        local a = spop()
        local t = new_ssa()
        local result = new_ssa()
        emit(string.format("%s = and i64 %s, %s", t, a, b))
        emit(string.format("%s = xor i64 %s, -1", result, t))
        spush(result)
        spush("0")

    elseif typ == "vNor" then
        local b = spop()
        local a = spop()
        local t = new_ssa()
        local result = new_ssa()
        emit(string.format("%s = or i64 %s, %s", t, a, b))
        emit(string.format("%s = xor i64 %s, -1", result, t))
        spush(result)
        spush("0")

    elseif typ == "vShr" or typ == "vShl" or typ == "vSar" then
        local b = spop()
        local a = spop()
        local result = new_ssa()
        local op_map = { vShr="lshr", vShl="shl", vSar="ashr" }
        emit(string.format("%s = %s i64 %s, %s", result, op_map[typ], a, b))
        spush(result)
        spush("0")

    elseif typ == "vNot" then
        local a = spop()
        local result = new_ssa()
        emit(string.format("%s = xor i64 %s, -1", result, a))
        spush(result)
        spush("0")

    elseif typ == "vNeg" then
        local a = spop()
        local result = new_ssa()
        emit(string.format("%s = sub i64 0, %s", result, a))
        spush(result)
        spush("0")

    elseif typ == "vMul" or typ == "vImul" then
        local b = spop()
        local a = spop()
        local result = new_ssa()
        emit(string.format("%s = mul i64 %s, %s", result, a, b))
        spush(result)
        spush("0")

    elseif typ:match("^vStore") then
        local addr = spop()
        local val  = spop()
        local bits = typ:match("vStore(%d+)")
        local ptr = new_ssa()
        emit(string.format("%s = inttoptr i64 %s to ptr", ptr, addr))
        if bits == "8" then
            local t = new_ssa()
            emit(string.format("%s = trunc i64 %s to i8", t, val))
            emit(string.format("store i8 %s, ptr %s", t, ptr))
        elseif bits == "16" then
            local t = new_ssa()
            emit(string.format("%s = trunc i64 %s to i16", t, val))
            emit(string.format("store i16 %s, ptr %s", t, ptr))
        elseif bits == "32" then
            local t = new_ssa()
            emit(string.format("%s = trunc i64 %s to i32", t, val))
            emit(string.format("store i32 %s, ptr %s", t, ptr))
        else
            emit(string.format("store i64 %s, ptr %s", val, ptr))
        end

    elseif typ:match("^vLoad") then
        local addr = spop()
        local bits = typ:match("vLoad(%d+)")
        local ptr = new_ssa()
        emit(string.format("%s = inttoptr i64 %s to ptr", ptr, addr))
        if bits == "8" then
            local t = new_ssa()
            emit(string.format("%s = load i8, ptr %s", t, ptr))
            local ext = new_ssa()
            emit(string.format("%s = zext i8 %s to i64", ext, t))
            spush(ext)
        elseif bits == "16" then
            local t = new_ssa()
            emit(string.format("%s = load i16, ptr %s", t, ptr))
            local ext = new_ssa()
            emit(string.format("%s = zext i16 %s to i64", ext, t))
            spush(ext)
        elseif bits == "32" then
            local t = new_ssa()
            emit(string.format("%s = load i32, ptr %s", t, ptr))
            local ext = new_ssa()
            emit(string.format("%s = zext i32 %s to i64", ext, t))
            spush(ext)
        else
            local v = new_ssa()
            emit(string.format("%s = load i64, ptr %s", v, ptr))
            spush(v)
        end

    elseif typ == "vExit" then
        emit("; vExit")
    elseif typ == "vOp" then
        emit("; vOp (unrecognized)")
    elseif typ == "unknown" then
        emit("; unknown handler")
    end
end

-- 写回 EXIT 寄存器到 struct
emit("")
emit("; write only modified registers back to context struct")
for off, reg in pairs(off_to_exit) do
    if reg ~= "rflags" and offset_set[off] and reg_to_idx[reg] and modified_slots[off] then
        local v = new_ssa()
        local gep = new_ssa()
        emit(string.format("%s = load i64, ptr %%%s", v, slot_name(off)))
        emit(string.format("%s = getelementptr inbounds %%struct.CpuState, ptr %%ctx, i32 0, i32 %d", gep, reg_to_idx[reg]))
        emit(string.format("store i64 %s, ptr %s  ; %s", v, gep, reg))
    end
end

emit("ret void")
table.insert(ir, "}")

local output = table.concat(ir, "\n") .. "\n"

local out_path = "vmp_lifted.ll"
local f = io.open(out_path, "w")
if f then
    f:write(output)
    f:close()
    log(string.format("[ok] LLVM IR → %s (%d 行, 栈剩余 %d)", out_path, #ir, #stack))
else
    log(string.format("[error] 无法写入 %s", out_path))
end
